/* ------------------------------------------------------------------
 * Austria Family Trip — trip data
 * ------------------------------------------------------------------
 * Everything the app renders lives in this one object, so you can edit
 * the trip without touching app logic.
 *
 * Loaded as a plain script (window.TRIP_DATA) instead of a fetched
 * data.json on purpose: it works when you open index.html straight off
 * the filesystem, with no CORS/fetch failures.
 *
 * NAVIGATION: each place needs either
 *    coords:   { lat, lng }        -> most precise, used for distances
 *    navQuery: "Name, Town, AT"   -> overrides coords for the map link
 *                                    (better for restaurants/hotels,
 *                                     where a name search beats a pin)
 *
 * FIELDS on an attraction:
 *    id, name, category, region, coords, priority, duration,
 *    weather ('sun' | 'rain' | 'any'), description, travelNote, tags
 * ------------------------------------------------------------------ */

window.TRIP_DATA = {
  trip: {
    title: "אוסטריה 2026",
    subtitle: "וינה · אזור זלצבורג · וינה",
    startDate: "2026-08-17",
    endDate: "2026-08-28",
    travellers: "טיול משפחתי",
    // Shown as a banner in the app — delete once you've checked the data.
    dataNote:
      "מאגר נתונים לדוגמה. הקואורדינטות, שעות הפתיחה והמחירים הם מיטב הידיעה וכדאי לאמת אותם לפני שמסתמכים עליהם.",
  },

  /* ---------------- FLIGHTS ---------------- */
  flights: [
    {
      id: "flt-out",
      label: "טיסת הלוך",
      date: "2026-08-17",
      from: { code: "TLV", city: "תל אביב", airport: "Ben Gurion" },
      to: { code: "VIE", city: "וינה", airport: "Vienna Intl." },
      departTime: "—:—",
      arriveTime: "—:—",
      flightNo: "TBD",
      terminal: "T3 (TLV) → T3 (VIE)",
      notes: "יש להוסיף מספר טיסה ושעות לאחר הכרטוס. להגיע לנתב\"ג 3 שעות לפני ההמראה.",
      navQuery: "Ben Gurion Airport Terminal 3, Israel",
    },
    {
      id: "flt-ret",
      label: "טיסת חזור",
      date: "2026-08-28",
      from: { code: "VIE", city: "וינה", airport: "Vienna Intl." },
      to: { code: "TLV", city: "תל אביב", airport: "Ben Gurion" },
      departTime: "—:—",
      arriveTime: "—:—",
      flightNo: "TBD",
      terminal: "T3 (VIE)",
      notes:
        "שדה התעופה של וינה במרחק ~20 דק׳ ברכבת CAT/S7 מ-Wien Mitte, ~25 דק׳ ברכב ממרכז העיר.",
      navQuery: "Vienna International Airport, Schwechat, Austria",
    },
  ],

  /* ---------------- CAR RENTAL ---------------- */
  carRental: {
    company: "טרם נקבע",
    confirmation: "טרם נקבע",
    vehicleNote: "כדאי להזמין סטיישן/7 מקומות אם רוצים מקום למזוודות ונוחות באלפים.",
    pickup: {
      label: "איסוף",
      date: "2026-08-18",
      time: "09:00",
      place: "שדה התעופה של וינה — מרכז השכרת הרכב",
      address: "Vienna International Airport, 1300 Wien-Flughafen, Austria",
      coords: { lat: 48.1213, lng: 16.5632 },
      navQuery: "Vienna Airport Car Rental Center, Schwechat, Austria",
      notes:
        "עמדות ההשכרה נמצאות בחניון הרב-קומתי מול טרמינל 3. יש לקנות מדבקת כביש מהיר אוסטרית (וינייטה) אם אינה כבר על השמשה (10 ימים ~€12).",
    },
    dropoff: {
      label: "החזרה",
      date: "2026-08-25",
      time: "17:00",
      place: "העיר וינה — סניף Wien Hauptbahnhof",
      address: "Am Hauptbahnhof, 1100 Wien, Austria",
      coords: { lat: 48.1852, lng: 16.3766 },
      navQuery: "Wien Hauptbahnhof, Vienna, Austria",
      notes:
        "החזרת הרכב עם ההגעה לוינה חוסכת 3 ימי חניה בעיר (~€30 ליום). אפשר לשנות להחזרה בשדה התעופה ב-28.08 אם מעדיפים לשמור על הרכב.",
    },
  },

  /* ---------------- ACCOMMODATION ---------------- */
  accommodations: [
    {
      id: "acc-moxy",
      name: "Moxy Vienna Airport",
      city: "שווכאט (שדה התעופה)",
      address: "Concorde Business Park, 2320 Schwechat, Austria",
      navQuery: "Moxy Vienna Airport, Schwechat, Austria",
      coords: { lat: 48.1268, lng: 16.5307 },
      checkIn: "2026-08-17",
      checkOut: "2026-08-18",
      checkInTime: "15:00",
      checkOutTime: "12:00",
      nights: 1,
      phone: "",
      notes:
        "לילה של הנחיתה בלבד. שאטל חינם 24 שעות מ/אל טרמינל 3 — בדקו את נקודת האיסוף לפני שיוצאים מאולם הנוסעים הנכנסים.",
    },
    {
      id: "acc-barbarahof",
      name: "Haus Barbarahof",
      city: "אלטנמרקט אים פונגאו",
      address: "Michael-Walchhofer-Straße 2, 5541 Altenmarkt im Pongau, Austria",
      navQuery: "Haus Barbarahof, Michael-Walchhofer-Straße 2, Altenmarkt im Pongau, Austria",
      coords: { lat: 47.3778, lng: 13.4222 },
      checkIn: "2026-08-18",
      checkOut: "2026-08-25",
      checkInTime: "15:00",
      checkOutTime: "10:00",
      nights: 7,
      phone: "",
      notes:
        "בסיס אלפיני לשבוע. שאלו על כרטיס האורח Salzburger Sportwelt — לרוב כולל רכבלים, בריכות ואוטובוסים. Therme Amadé במרחק נסיעה של 5 דק׳.",
    },
    {
      id: "acc-rafael",
      name: "RAFAEL KAISER",
      city: "וינה",
      address: "Vienna, Austria",
      navQuery: "Rafael Kaiser Apartments, Vienna, Austria",
      coords: { lat: 48.1979, lng: 16.3554 },
      checkIn: "2026-08-25",
      checkOut: "2026-08-28",
      checkInTime: "15:00",
      checkOutTime: "11:00",
      nights: 3,
      phone: "",
      notes:
        "סיום בעיר. אמתו את כתובת הרחוב המדויקת וקוד הצ׳ק-אין העצמי מול המארח — בבנייני דירות לרוב אין קבלה.",
    },
  ],

  /* ---------------- LONG DRIVE SEGMENTS + STOPOVERS ---------------- */
  drives: [
    {
      id: "drv-arrive",
      date: "2026-08-17",
      title: "שדה התעופה → מלון Moxy",
      titleLatin: "Airport → Moxy Vienna Airport",
      from: "Vienna Airport (VIE)",
      to: "Moxy Vienna Airport",
      distanceKm: 4,
      durationText: "~10 דק׳ (שאטל חינם של המלון)",
      summary: "נחיתה, שאטל, שינה. אין צורך בעצירות.",
      stopovers: [],
    },
    {
      id: "drv-west",
      date: "2026-08-18",
      title: "וינה → אלטנמרקט אים פונגאו",
      titleLatin: "Vienna → Altenmarkt im Pongau",
      from: "Vienna Airport",
      to: "Haus Barbarahof, Altenmarkt",
      distanceKm: 335,
      durationText: "~3 שעות 20 דק׳ ברצף (A1 → A10)",
      summary:
        "אספו את הרכב מוקדם והפכו את היום ליום טיולים: מלק או עמק ואכאו בבוקר, ארוחת צהריים ליד מונדזה, והגעה לאלטנמרקט לצ׳ק-אין.",
      stopovers: [
        {
          name: "מנזר מלק",
          nameLatin: "Stift Melk (Melk Abbey)",
          coords: { lat: 48.2281, lng: 15.3336 },
          detour: "0 דק׳ — ממש ליד ה-A1",
          duration: "1.5–2 h",
          why: "מנזר בארוקי מעל הדנובה; הגנים נוחים עם ילדים. ~שעה משדה התעופה, עצירה מושלמת למקטע הראשון.",
        },
        {
          name: "דירנשטיין, עמק ואכאו",
          nameLatin: "Dürnstein, Wachau Valley",
          coords: { lat: 48.3958, lng: 15.5192 },
          detour: "+35 דק׳",
          duration: "1–1.5 h",
          why: "מגדל כנסייה כחול, משמש בכל פינה, וטירה הרוסה מעל הכרמים. חלופה נופית לכביש המהיר.",
        },
        {
          name: "חוף אגם מונדזה",
          nameLatin: "Mondsee lakefront",
          coords: { lat: 47.8564, lng: 13.3494 },
          detour: "+10 דק׳",
          duration: "1 h",
          why: "עצירת שחייה וארוחת צהריים בערך באמצע הדרך, עם חוף אגם אמיתי. הבזיליקה היא כנסיית החתונה מ׳צלילי המוזיקה׳.",
        },
        {
          name: "מפל גולינג",
          nameLatin: "Gollinger Wasserfall",
          coords: { lat: 47.5842, lng: 13.1592 },
          detour: "+15 דק׳ מה-A10",
          duration: "1–1.5 h",
          why: "מפל דו-קומתי, הליכה של 20 דק׳ מהחניה. מרענן את כולם לפני שעת הנסיעה האחרונה.",
        },
      ],
    },
    {
      id: "drv-east",
      date: "2026-08-25",
      title: "אלטנמרקט → וינה",
      titleLatin: "Altenmarkt → Vienna",
      from: "Haus Barbarahof, Altenmarkt",
      to: "RAFAEL KAISER, Vienna",
      distanceKm: 320,
      durationText: "~3 שעות 15 דק׳ ברצף (A10 → A1)",
      summary:
        "צ׳ק-אאוט ב-10:00, עצירת בוקר גדולה אחת, ארוחת צהריים, ואז נוסעים ברצף. הרכב חוזר ב-Wien Hauptbahnhof בסביבות 17:00 — השאירו זמן לתדלוק.",
      stopovers: [
        {
          name: "מבצר הוהנוורפן",
          nameLatin: "Festung Hohenwerfen",
          coords: { lat: 47.4794, lng: 13.1892 },
          detour: "0 דק׳ — 30 דק׳ מאלטנמרקט, על ה-A10",
          duration: "2–3 h",
          why: "מבצר על צוק עם מיצג בזים. עצירת ׳בדרך הביתה׳ הטובה ביותר של כל הטיול.",
        },
        {
          name: "העיר העתיקה של זלצבורג",
          nameLatin: "Salzburg old town",
          coords: { lat: 47.7982, lng: 13.0458 },
          detour: "+30 דק׳",
          duration: "3–4 h",
          why: "אם דילגתם על זלצבורג במהלך השבוע, זו ההזדמנות האחרונה. חנו בחניון Altstadtgarage Mönchsberg.",
        },
        {
          name: "סנט גילגן / וולפגנגזה",
          nameLatin: "St. Gilgen / Wolfgangsee",
          coords: { lat: 47.7683, lng: 13.3675 },
          detour: "+20 דק׳",
          duration: "1.5–2 h",
          why: "שחייה באגם ורכבל הצוולפרהורן. הכי טוב בשילוב עם יציאה מוקדמת.",
        },
        {
          name: "מנזר מלק (אם לא ביקרתם בדרך הלוך)",
          nameLatin: "Stift Melk",
          coords: { lat: 48.2281, lng: 15.3336 },
          detour: "0 דק׳",
          duration: "1.5 h",
          why: "העצירה הקלה האחרונה לפני פקקי וינה; שעה מהעיר.",
        },
        {
          name: "מערת האגם זגרוטה הינטרברול",
          nameLatin: "Seegrotte Hinterbrühl",
          coords: { lat: 48.0619, lng: 16.2472 },
          detour: "+20 דק׳, ממש מחוץ לוינה",
          duration: "1.5 h",
          why: "שיט על האגם התת-קרקעי הגדול באירופה. 9°C שם למטה — קחו מעיל. תוכנית מצוינת להגעה ביום גשום.",
        },
      ],
    },
    {
      id: "drv-depart",
      date: "2026-08-28",
      title: "וינה → שדה התעופה (יציאה)",
      titleLatin: "Vienna → Airport (departure)",
      from: "RAFAEL KAISER, Vienna",
      to: "Vienna Airport (VIE)",
      distanceKm: 20,
      durationText: "~25 דק׳ ברכב / 16 דק׳ ברכבת CAT מ-Wien Mitte",
      summary:
        "הרכב כבר הוחזר — סעו ב-S7 (זול, ~€4.20) או ב-CAT מ-Wien Mitte, או במונית/Bolt בכ-€35–45. צאו 3 שעות לפני ההמראה.",
      stopovers: [],
    },
  ],

  /* ---------------- FILTER VOCABULARY ---------------- */
  categories: [
    { id: "coaster", label: "מגלשות הרים", icon: "🛷" },
    { id: "water", label: "מים וספא", icon: "🏊" },
    { id: "nature", label: "טבע וקניונים", icon: "⛰️" },
    { id: "castle", label: "טירות ויום גשום", icon: "🏰" },
    { id: "vienna", label: "החובה בווינה", icon: "🎡" },
    { id: "food", label: "אוכל ומסעדות", icon: "🍽️" },
  ],

  regions: [
    { id: "salzburgerland", label: "אזור זלצבורג" },
    { id: "vienna", label: "וינה" },
    { id: "enroute", label: "על הדרך" },
  ],

  priorities: [
    { id: "must", label: "חובה", rank: 3 },
    { id: "high", label: "גבוהה", rank: 2 },
    { id: "optional", label: "אופציונלי", rank: 1 },
  ],

  /* ---------------- THE ATTRACTION BANK ---------------- */
  attractions: [
    /* ===== ALPINE COASTERS ===== */
    {
      id: "co-lucky-flitzer",
      name: "מגלשת ההרים לאקי פליצר, פלאכאו",
      nameLatin: "Lucky Flitzer Alpine Coaster, Flachau",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.3457, lng: 13.3877 },
      priority: "must",
      duration: "2–3 h",
      weather: "sun",
      travelNote: "~12 דק׳ מאלטנמרקט",
      description:
        "1,000 מ׳ של סיבובים משופעים וקפיצות ליד רכבל Space Jet. מגלשת ההרים הקרובה ביותר לבית — ילדים מגיל ~3 רוכבים בזוג עם מבוגר. שלבו עם גן המשחקים הקיצי של פלאכאו.",
      tags: ["kids", "gondola", "closest"],
    },
    {
      id: "co-rittisberg",
      name: "מגלשת ריטיסברג, רמזאו אם דכשטיין",
      nameLatin: "Rittisberg Coaster, Ramsau am Dachstein",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.4083, lng: 13.6427 },
      priority: "high",
      duration: "half day",
      weather: "sun",
      travelNote: "~45 דק׳ מאלטנמרקט",
      description:
        "מגלשה באורך 1.3 ק״מ ובנוסף גן שעשועים הררי גדול באמת, בריכת מים ומסלול טיול מעגלי — האופציה הטובה ביותר ל׳להישאר כל אחר הצהריים׳, עם קיר הדכשטיין ברקע.",
      tags: ["kids", "playground"],
    },
    {
      id: "co-karkogel",
      name: "מגלשת קרקוגל, אבטנאו",
      nameLatin: "Sommerrodelbahn Karkogel, Abtenau",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.561, lng: 13.345 },
      priority: "optional",
      duration: "2 h",
      weather: "sun",
      travelNote: "~40 דק׳ מאלטנמרקט",
      description:
        "מגלשת קיץ קלאסית על מסילה בודדת עם רכבל כיסא בחזרה למעלה. שקטה יותר מפלאכאו; משתלבת יפה עם בוקר בקניון לאמרקלאם.",
      tags: ["kids", "chairlift"],
    },
    {
      id: "co-grafenberg",
      name: "וגראיניס גרפנברג (פליינג פוקס ומסלולים)",
      nameLatin: "Wagrainis Grafenberg (Flying Fox & trails)",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.3336, lng: 13.2986 },
      priority: "high",
      duration: "half day",
      weather: "sun",
      travelNote: "~15 דק׳ מאלטנמרקט",
      description:
        "רכבלית אל הר שלם של אטרקציות משפחתיות: פליינג פוקס, אזור משחקי מים, מסלולים נושאיים ועגלות הרים. לא בדיוק מגלשת הרים, אבל אותה אנרגיה וקרוב מאוד.",
      tags: ["kids", "gondola", "closest"],
    },
    {
      id: "co-nocky",
      name: "נוקי פליצר, טוראכר הֵה",
      nameLatin: "Nocky Flitzer, Turracher Höhe",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 46.9111, lng: 13.8828 },
      priority: "optional",
      duration: "full day",
      weather: "sun",
      travelNote: "~שעה 40 דק׳ מאלטנמרקט",
      description:
        "מגלשת ההרים המצולמת ביותר באוסטריה — לולאות 360° עם הרי הנוקברגה ברקע. שווה רק כטיול של יום שלם; המסלול בפלאכאו קרוב ב-90 דקות.",
      tags: ["scenic", "far"],
    },
    {
      id: "co-planai",
      name: "פלנאי הופסילנד ורכבלי הקיץ, שלאדמינג",
      nameLatin: "Planai Hopsiland & summer lifts, Schladming",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.3928, lng: 13.6883 },
      priority: "optional",
      duration: "half day",
      weather: "sun",
      travelNote: "~35 דק׳ מאלטנמרקט",
      description:
        "רכבל אל עולם גן משחקים בפסגת ההר (הופסילנד) עם משחקי מים ומגלשה ענקית. יום טוב של נעליים רטובות ומגבת.",
      tags: ["kids", "cable car"],
    },
    {
      id: "co-geisterberg",
      name: "הר הרוחות גייסטרברג, סנט יוהאן (אלפנדורף)",
      nameLatin: "Geisterberg, St. Johann im Pongau (Alpendorf)",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.3106, lng: 13.2478 },
      navQuery: "Geisterberg, Alpendorf, St. Johann im Pongau, Austria",
      priority: "high",
      duration: "3–4 h",
      weather: "sun",
      travelNote: "~20 דק׳ מאלטנמרקט",
      description:
        "עולם הרפתקאות בפסגה עם עשרות תחנות משחק, מגלשות, מתקני מים ומסלול ׳רוחות׳ סביב אגם הרים. עולים ברכבל מאלפנדורף. חצי יום כיף לילדים.",
      tags: ["kids", "gondola", "adventure"],
    },
    {
      id: "co-fantasiana",
      name: "פארק השעשועים פנטזיאנה, שטרסוואלכן",
      nameLatin: "Fantasiana Erlebnispark Straßwalchen",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.9711, lng: 13.2564 },
      navQuery: "Fantasiana Erlebnispark Straßwalchen, Austria",
      priority: "high",
      duration: "4–6 h",
      weather: "sun",
      travelNote: "~שעה 15 דק׳ מאלטנמרקט",
      description:
        "פארק שעשועים משפחתי צפונית לזלצבורג עם רכבות הרים קלות, מתקנים נושאיים, מופעים ואזורי משחק — מתאים במיוחד לגילאי 6–12. נסיעה ארוכה יחסית, שמרו ליום שלם.",
      tags: ["kids", "far"],
    },
    {
      id: "co-erlebniswald",
      name: "פארק החבלים ביער, אלטנמרקט",
      nameLatin: "Erlebniswald Altenmarkt (forest rope park)",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.3725, lng: 13.4165 },
      navQuery: "Erlebniswald Altenmarkt, Austria",
      priority: "high",
      duration: "3–4 h",
      weather: "sun",
      travelNote: "~5 דק׳ מהבית",
      description:
        "פארק טיפוס וחבלים ביער ממש ליד הבית, מסלולים בגבהים שונים לגילאים שונים. פתוח בעונה שלכם (8.7–11.9), לרוב 10:00–16:30. מעולה לילדים בני 7 ו-10 — כניסה עד 90 דק׳ לפני הסגירה.",
      tags: ["kids", "adventure", "closest"],
    },
    {
      id: "co-flori",
      name: "שביל החוויה של פלורי, פלאכאו",
      nameLatin: "Flori's Erlebnispfad, Flachau",
      category: "coaster",
      region: "salzburgerland",
      coords: { lat: 47.341, lng: 13.386 },
      navQuery: "Flori's Erlebnispfad, Flachau, Austria",
      priority: "optional",
      duration: "2 h",
      weather: "sun",
      travelNote: "~15 דק׳ מאלטנמרקט",
      description:
        "מסלול חוויה נושאי למשפחות בפסגת פלאכאו עם תחנות משחק והתנסות לאורך הדרך. שילוב טבעי עם יום ב-Lucky Flitzer ובאזור ה-Space Jet.",
      tags: ["kids", "easy hike", "closest"],
    },

    /* ===== WATER & THERME ===== */
    {
      id: "wa-therme-amade",
      name: "טרמה אמדה, אלטנמרקט",
      nameLatin: "Erlebnis-Therme Amadé, Altenmarkt",
      category: "water",
      region: "salzburgerland",
      coords: { lat: 47.3752, lng: 13.42 },
      priority: "must",
      duration: "3–5 h",
      weather: "rain",
      travelNote: "~5 דק׳ מאלטנמרקט",
      description:
        "התשובה שמתבקשת ליום גשום, 5 דקות מהבית: בריכות מקורות וחיצוניות, מגלשות, אזור ילדים ועולם סאונות. בדקו אם כרטיס האורח כולל כניסה.",
      tags: ["rainy day", "kids", "closest", "indoor"],
    },
    {
      id: "wa-alpentherme",
      name: "אלפנטרמה גשטיין, בד הופגשטיין",
      nameLatin: "Alpentherme Gastein, Bad Hofgastein",
      category: "water",
      region: "salzburgerland",
      coords: { lat: 47.1683, lng: 13.0983 },
      priority: "high",
      duration: "half day",
      weather: "rain",
      travelNote: "~50 דק׳ מאלטנמרקט",
      description:
        "מתחם תרמי גדול בהרבה עם עולם משפחתי ייעודי, בריכת גלים ולגונה תרמית חיצונית. שווה את הנסיעה אם אמדה מרגישה קטנה או עמוסה.",
      tags: ["rainy day", "kids", "indoor", "thermal"],
    },
    {
      id: "wa-aqua-salza",
      name: "אקווה סלצה, גולינג",
      nameLatin: "Aqua Salza, Golling",
      category: "water",
      region: "salzburgerland",
      coords: { lat: 47.5983, lng: 13.1642 },
      priority: "optional",
      duration: "3 h",
      weather: "rain",
      travelNote: "~35 דק׳ מאלטנמרקט",
      description:
        "בריכת הרפתקאות בגודל בינוני עם מגלשות וקיר טיפוס. שימושית כתוכנית גשם שמתלבשת על בוקר במפל גולינג או בהוהנוורפן.",
      tags: ["rainy day", "kids", "indoor"],
    },
    {
      id: "wa-zauchensee",
      name: "אגם צאוכנזה וגמסקוגל",
      nameLatin: "Zauchensee lake & Gamskogel",
      category: "water",
      region: "salzburgerland",
      coords: { lat: 47.2963, lng: 13.4438 },
      priority: "high",
      duration: "3–4 h",
      weather: "sun",
      travelNote: "~20 דק׳ מאלטנמרקט",
      description:
        "אגם אלפיני קטן שמוקף במסלול מעגלי קל שמתאים לעגלה, עם רכבל כיסא במעלה הגמסקוגל לתצפית. זול, קרוב ויפה באור הבוקר.",
      tags: ["easy hike", "lake", "closest"],
    },
    {
      id: "wa-jaegersee",
      name: "אגם יגרזה, קליינארל",
      nameLatin: "Jägersee, Kleinarl",
      category: "water",
      region: "salzburgerland",
      coords: { lat: 47.2664, lng: 13.3419 },
      priority: "must",
      duration: "2–4 h",
      weather: "sun",
      travelNote: "~25 דק׳ מאלטנמרקט",
      description:
        "אגם הררי כמו מגלויה עם טיילת שטוחה של 30 דק׳ לאורך החוף וגסטהוף שמגיש פורל בסופה. המשיכו לטאפנקרזה רק אם בא לכם טרק רציני.",
      tags: ["easy hike", "lake", "photo"],
    },
    {
      id: "wa-wolfgangsee",
      name: "אגם וולפגנגזה בסנט גילגן",
      nameLatin: "Wolfgangsee at St. Gilgen",
      category: "water",
      region: "salzburgerland",
      coords: { lat: 47.7683, lng: 13.3675 },
      priority: "high",
      duration: "full day",
      weather: "sun",
      travelNote: "~שעה 10 דק׳ מאלטנמרקט",
      description:
        "אגם חמים שאפשר לשחות בו עם חוף רחצה אמיתי, שיט לסנט וולפגנג ורכבל הצוולפרהורן מעליו. הכי טוב כעצירה בדרך חזרה ב-25.08.",
      tags: ["swimming", "boat", "cable car"],
    },
    {
      id: "wa-freibad-radstadt",
      name: "בריכה חיצונית פרייבאד, רדשטאדט",
      nameLatin: "Freibad Radstadt (outdoor pool)",
      category: "water",
      region: "salzburgerland",
      coords: { lat: 47.3856, lng: 13.4553 },
      priority: "optional",
      duration: "2–3 h",
      weather: "sun",
      travelNote: "~8 דק׳ מאלטנמרקט",
      description:
        "בריכה חיצונית זולה בכפר עם מדשאות ונוף הרים — פתרון של אחר צהריים חם וללא מאמץ, כשאף אחד לא רוצה לנסוע לשום מקום.",
      tags: ["kids", "cheap", "closest"],
    },
    {
      id: "wa-donauinsel",
      name: "חוף קופה / דונאואינזל, וינה",
      nameLatin: "Copa Beach / Donauinsel, Vienna",
      category: "water",
      region: "vienna",
      coords: { lat: 48.2246, lng: 16.4048 },
      priority: "high",
      duration: "2–4 h",
      weather: "sun",
      travelNote: "רכבת U1 דונאואינזל, ~15 דק׳ מהמרכז",
      description:
        "חוף נהר חינמי בלב העיר — מים רדודים, שבילי אופניים, אוכל רחוב. מושלם כשסתום לחץ אחרי יום עתיר מוזיאונים בוינה.",
      tags: ["free", "kids", "swimming"],
    },
    {
      id: "wa-gaensehaeufel",
      name: "אי הרחצה גנזהויפל, וינה",
      nameLatin: "Gänsehäufel bathing island, Vienna",
      category: "water",
      region: "vienna",
      coords: { lat: 48.2247, lng: 16.4306 },
      priority: "optional",
      duration: "half day",
      weather: "sun",
      travelNote: "רכבת U1 קייזרמולן + אוטובוס, ~25 דק׳",
      description:
        "הלידו הקלאסי הגדול של וינה על הדנובה הישנה: מדשאות, מגלשות, בריכות ילדים רדודות ותאי הלבשה. בחירת המקומיים ביום של 32°C.",
      tags: ["kids", "swimming"],
    },

    /* ===== NATURE & GORGES ===== */
    {
      id: "na-liechtensteinklamm",
      name: "קניון ליכטנשטיין, סנט יוהאן אים פונגאו",
      nameLatin: "Liechtensteinklamm, St. Johann im Pongau",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.3164, lng: 13.2011 },
      priority: "must",
      duration: "1.5–2 h",
      weather: "any",
      travelNote: "~20 דק׳ מאלטנמרקט",
      description:
        "הקניון המרכזי של האזור: קירות בגובה 300 מ׳, מדרגות לוליניות מעל הזרם ושביל משוחזר עד המפל. קריר ומוצל — עובד בגשם קל ובימים חמים. פתוח בקיץ 09:00–18:00; הגיעו בסביבות 09:30.",
      tags: ["gorge", "easy hike", "closest", "photo"],
    },
    {
      id: "na-eisriesenwelt",
      name: "מערת הקרח אייסריזנוולט, וורפן",
      nameLatin: "Eisriesenwelt Ice Cave, Werfen",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.5031, lng: 13.1897 },
      priority: "must",
      duration: "4 h door to door",
      weather: "any",
      travelNote: "~30 דק׳ מאלטנמרקט",
      description:
        "מערת הקרח הנגישה הגדולה בעולם: אוטובוס, רכבל ואז סיור מודרך של 700 מדרגות בין תצורות קרח לאור מנורת קרביד. 0°C בפנים — מעילים ונעליים אמיתיות, בלי עגלות.",
      tags: ["cave", "cable car", "warm clothes"],
    },
    {
      id: "na-lammerklamm",
      name: "קניון לאמרקלאם (לאמרפן), שפאו",
      nameLatin: "Lammerklamm (Lammeröfen), Scheffau",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.5983, lng: 13.2778 },
      priority: "high",
      duration: "1 h",
      weather: "any",
      travelNote: "~35 דק׳ מאלטנמרקט",
      description:
        "קניון סדק קצר ודרמטי על שבילי עץ מעל מים ירוקים גועשים. זול ומהיר — תוספת אידאלית לאבטנאו או גולינג.",
      tags: ["gorge", "short", "cheap"],
    },
    {
      id: "na-gollinger-wasserfall",
      name: "מפל גולינג",
      nameLatin: "Gollinger Wasserfall",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.5842, lng: 13.1592 },
      priority: "high",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~35 דק׳ מאלטנמרקט · על ה-A10 לוינה",
      description:
        "מפל דו-קומתי שמגיעים אליו בהליכה של 20 דק׳ ביער עם גשרים ורסס. מתפקד גם כעצירת פסק הרגליים הטובה ביותר בכל אחת מהנסיעות הארוכות.",
      tags: ["waterfall", "easy hike", "stopover"],
    },
    {
      id: "na-silberkarklamm",
      name: "קניון זילברקאר, רמזאו אם דכשטיין",
      nameLatin: "Silberkarklamm, Ramsau am Dachstein",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.4092, lng: 13.6606 },
      priority: "optional",
      duration: "2 h",
      weather: "any",
      travelNote: "~45 דק׳ מאלטנמרקט",
      description:
        "קניון פראי יותר ופחות מבוקר עם גשרים תלויים ובקתה בקצה העליון. שלבו עם מגלשת ריטיסברג ליום רמזאו מלא.",
      tags: ["gorge", "hike"],
    },
    {
      id: "na-talbachklamm",
      name: "קניון טלבאך, שלאדמינג",
      nameLatin: "Talbachklamm, Schladming",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.3956, lng: 13.6836 },
      priority: "optional",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~35 דק׳ מאלטנמרקט",
      description:
        "טיול קניון שמתחיל מקצה העיר שלאדמינג — אין צורך בנסיעה נפרדת אם אתם כבר קונים או אוכלים שם.",
      tags: ["gorge", "easy hike"],
    },
    {
      id: "na-kitzlochklamm",
      name: "קניון קיצלוך, טקסנבאך",
      nameLatin: "Kitzlochklamm, Taxenbach",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.2903, lng: 12.9614 },
      priority: "optional",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~50 דק׳ מאלטנמרקט",
      description:
        "מנהרות, סולמות ומים גועשים — הכי הרפתקני מבין הקניונים הקרובים. טוב בדרך לצל אם זה או לגרוסגלוקנר.",
      tags: ["gorge", "adventure"],
    },
    {
      id: "na-krimml",
      name: "מפלי קרימל",
      nameLatin: "Krimml Waterfalls",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.2131, lng: 12.1683 },
      priority: "high",
      duration: "full day",
      weather: "sun",
      travelNote: "~שעה 45 דק׳ מאלטנמרקט",
      description:
        "המפל הגבוה באירופה בגובה 380 מ׳, מטפסים לצדו בשביל זיגזג עם תצפיות בתוך הרסס. הוסיפו את פארק המים WasserWelten בבסיס. נסיעה ארוכה — התחייבו ליום שלם.",
      tags: ["waterfall", "hike", "far"],
    },
    {
      id: "na-grossglockner",
      name: "כביש ההרים גרוסגלוקנר",
      nameLatin: "Grossglockner High Alpine Road",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.0742, lng: 12.7519 },
      priority: "high",
      duration: "full day",
      weather: "sun",
      travelNote: "~שעה 30 דק׳ עד שער האגרה מאלטנמרקט",
      description:
        "36 סרפנטינות עד לתצפיות הקרחון בקייזר-פרנץ-יוזפס-הֵה, עם מרמוטות, תערוכות ומסלולים קצרים בדרך. אגרה ~€40 לרכב. סעו רק ביום בהיר — בערפל אתם משלמים על ערפל.",
      tags: ["scenic drive", "toll", "clear day only"],
    },
    {
      id: "na-krippenstein",
      name: "דכשטיין קריפנשטיין ו-5fingers",
      nameLatin: "Dachstein Krippenstein & 5fingers",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.5108, lng: 13.69 },
      priority: "high",
      duration: "full day",
      weather: "sun",
      travelNote: "~שעה 15 דק׳ מאלטנמרקט",
      description:
        "רכבל אל תצפית ה-5fingers מעל הלשטאט, ובנוסף מערת הקרח הענקית ומערת הממותה. שלבו עם הכפר הלשטאט אבל צפו לצפיפות.",
      tags: ["cable car", "cave", "photo"],
    },
    {
      id: "na-dachstein-skywalk",
      name: "דכשטיין סקיווק וארמון הקרח",
      nameLatin: "Dachstein Glacier Skywalk & Ice Palace",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.4756, lng: 13.6069 },
      priority: "high",
      duration: "half day",
      weather: "sun",
      travelNote: "~50 דק׳ מאלטנמרקט",
      description:
        "רכבל ל-2,700 מ׳: גשר תלוי, ׳מדרגות אל האין׳, ארמון קרח ושלג באוגוסט. קחו שכבות חמות גם בגל חום.",
      tags: ["cable car", "snow", "warm clothes"],
    },
    {
      id: "na-hallstatt",
      name: "הכפר והאגם הלשטאט",
      nameLatin: "Hallstatt village & lake",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.5622, lng: 13.6493 },
      priority: "high",
      duration: "half day",
      weather: "any",
      travelNote: "~שעה 10 דק׳ מאלטנמרקט",
      description:
        "הכפר המפורסם שלחוף האגם, עם תצפיות, שיט וגלידה. ⚠️ מכרה המלח והסקיווק סגורים לעבודות עד 1.9.2026 — בואו בשביל הכפר והאגם, לא בשביל המכרה (חלופה: מכרה המלח באלטאאוסה). הגיעו לפני 09:30 או אחרי 16:00; החניה בתשלום ומוגבלת.",
      tags: ["photo", "crowded", "lake"],
    },
    {
      id: "na-filzmoos-almen",
      name: "אוברהופאלם ואונטרהופאלם, פילצמוס",
      nameLatin: "Oberhofalm & Unterhofalm, Filzmoos",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.4361, lng: 13.5228 },
      priority: "must",
      duration: "3–4 h",
      weather: "sun",
      travelNote: "~25 דק׳ מאלטנמרקט",
      description:
        "אחו פרחים ובקתות עץ מתחת לבישופסמיצה — התמונה הקלאסית של אזור זלצבורג. עלו ברכב (אגרה קטנה), הלכו את המסלול הקל בין שתי הבקתות, אכלו קייזרשמארן.",
      tags: ["easy hike", "photo", "hut food"],
    },
    {
      id: "na-untersberg",
      name: "רכבל אונטרסברג, גרֵדיג",
      nameLatin: "Untersbergbahn cable car, Grödig",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.7092, lng: 13.0322 },
      priority: "optional",
      duration: "3 h",
      weather: "sun",
      travelNote: "~שעה מאלטנמרקט · 15 דק׳ מזלצבורג",
      description:
        "רכבל של שמונה דקות ל-1,776 מ׳ עם זלצבורג והאלפים פרוסים מתחת. תוספת קלה ליום בזלצבורג כשמתחמם מדי בעיר.",
      tags: ["cable car", "view"],
    },
    {
      id: "na-lainzer",
      name: "שמורת ליינצר טירגרטן, וינה",
      nameLatin: "Lainzer Tiergarten, Vienna",
      category: "nature",
      region: "vienna",
      coords: { lat: 48.175, lng: 16.25 },
      priority: "optional",
      duration: "2–3 h",
      weather: "sun",
      travelNote: "~30 דק׳ מהמרכז",
      description:
        "שטח ציד קיסרי לשעבר מוקף חומה בקצה העיר: חזירי בר ואיילים משוטטים חופשי, שבילים מוצלים, גן שעשועים והרמסווילה. כניסה חינם.",
      tags: ["free", "kids", "wildlife"],
    },
    {
      id: "na-kahlenberg",
      name: "תצפית קאהלנברג, וינה",
      nameLatin: "Kahlenberg viewpoint, Vienna",
      category: "nature",
      region: "vienna",
      coords: { lat: 48.2664, lng: 16.3336 },
      priority: "optional",
      duration: "1.5 h",
      weather: "sun",
      travelNote: "~25 דק׳ ברכב מהמרכז",
      description:
        "גבעת כרמים עם כל העיר והדנובה מתחתיה. הכי טוב בשקיעה, רצוי בהמשך לביקור בבית יין (הויריגר) בגרינצינג בדרך למטה.",
      tags: ["free", "view", "sunset"],
    },
    {
      id: "na-gosausee",
      name: "אגם גוזאו (Vorderer Gosausee)",
      nameLatin: "Gosausee, Gosau",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.5253, lng: 13.4931 },
      navQuery: "Vorderer Gosausee, Gosau, Austria",
      priority: "must",
      duration: "2–3 h",
      weather: "sun",
      travelNote: "~שעה 15 דק׳ מאלטנמרקט",
      description:
        "אגם הררי צלול עם מסלול הליכה מעגלי שטוח (~שעה) ונוף ישיר לקרחון הדכשטיין. אפשר לשכור סירת פדלים ולהביא פיקניק. אחד הנופים היפים באזור.",
      tags: ["easy hike", "lake", "photo"],
    },
    {
      id: "na-sigmund-thun-klamm",
      name: "נקיק זיגמונד-תון, קפרון",
      nameLatin: "Sigmund-Thun-Klamm, Kaprun",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.2739, lng: 12.7561 },
      navQuery: "Sigmund-Thun-Klamm, Kaprun, Austria",
      priority: "high",
      duration: "1.5–2 h",
      weather: "any",
      travelNote: "~שעה 10 דק׳ מאלטנמרקט",
      description:
        "מסלול גשרי עץ קל מעל מים גועשים שמוביל לאגם קלמזה. קצר, מוצל ומרשים — שילוב טוב עם ביקור בקפרון או בצל אם זה.",
      tags: ["gorge", "easy hike", "lake"],
    },
    {
      id: "na-mirabell",
      name: "גני מירבל, זלצבורג",
      nameLatin: "Mirabellgarten, Salzburg",
      category: "nature",
      region: "salzburgerland",
      coords: { lat: 47.8058, lng: 13.0428 },
      navQuery: "Mirabellgarten, Salzburg, Austria",
      priority: "optional",
      duration: "1 h",
      weather: "sun",
      travelNote: "~55 דק׳ מאלטנמרקט",
      description:
        "גני ארמון בארוקיים חינמיים במרכז זלצבורג עם ערוגות פרחים, פסלים ונוף למבצר — אתר צילום מ׳צלילי המוזיקה׳. תוספת קלה לכל יום בעיר.",
      tags: ["free", "gardens", "photo"],
    },

    /* ===== CASTLES & RAINY DAY ===== */
    {
      id: "ca-hohenwerfen",
      name: "מבצר הוהנוורפן, וורפן",
      nameLatin: "Festung Hohenwerfen, Werfen",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.4794, lng: 13.1892 },
      priority: "must",
      duration: "3 h",
      weather: "any",
      travelNote: "~30 דק׳ מאלטנמרקט · על ה-A10",
      description:
        "מבצר בן 900 שנה על סלע עם מיצג בזים היסטורי (נשרים ונשרי זקן מעופפים מעל החצר), חדרי נשק ורכבל משופע למעלה. טירת המשפחה המשתלמת ביותר כאן.",
      tags: ["castle", "falconry", "kids", "stopover"],
    },
    {
      id: "ca-hohensalzburg",
      name: "מבצר הוהנזלצבורג, זלצבורג",
      nameLatin: "Hohensalzburg Fortress, Salzburg",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.795, lng: 13.0475 },
      priority: "high",
      duration: "2–3 h",
      weather: "any",
      travelNote: "~55 דק׳ מאלטנמרקט",
      description:
        "המבצר השלם הגדול באירופה, מגיעים אליו ברכבל משופע מהעיר העתיקה. מוזיאון בובות מריונטה, חומות ופנורמת עיר. בעיקר מקורה — בחירה מצוינת ליום גשום.",
      tags: ["castle", "funicular", "indoor"],
    },
    {
      id: "ca-salzwelten",
      name: "מכרה המלח זלצוולטן, האליין",
      nameLatin: "Salzwelten salt mine, Hallein",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.6844, lng: 13.0736 },
      priority: "must",
      duration: "3 h",
      weather: "rain",
      travelNote: "~50 דק׳ מאלטנמרקט",
      description:
        "לובשים סרבל, רוכבים ברכבת הכורים אל תוך ההר, מחליקים במגלשות עץ וחוצים אגם מלח תת-קרקעי ברפסודה. הפעילות הטובה ביותר ליום גשום באזור — ילדים זוכרים אותה שנים.",
      tags: ["rainy day", "kids", "underground", "indoor"],
    },
    {
      id: "ca-hellbrunn",
      name: "מזרקות הקסם הלברון, זלצבורג",
      nameLatin: "Hellbrunn Trick Fountains, Salzburg",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.7622, lng: 13.0631 },
      priority: "high",
      duration: "2–3 h",
      weather: "sun",
      travelNote: "~50 דק׳ מאלטנמרקט",
      description:
        "גן משחקי מים בן 400 שנה שבו המדריך מרטיב את כולם בכוונה — ובנוסף פארק חינם והפרגולה מ׳צלילי המוזיקה׳. תתכוננו להירטב; קחו חולצה להחלפה. באוגוסט פתוח 09:30–19:00 (כניסה אחרונה 18:00), ויש גם גן שעשועים גדול.",
      tags: ["kids", "gardens", "get wet"],
    },
    {
      id: "ca-haus-der-natur",
      name: "בית הטבע, זלצבורג",
      nameLatin: "Haus der Natur, Salzburg",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.8003, lng: 13.0392 },
      priority: "high",
      duration: "3–4 h",
      weather: "rain",
      travelNote: "~55 דק׳ מאלטנמרקט",
      description:
        "מוזיאון היסטוריה של הטבע ומדע ענק עם תחנות התנסות, אקווריום, בית זוחלים, אולם דינוזאורים וקומה שלמה של ניסויים. ממלא בקלות יום גשום.",
      tags: ["rainy day", "museum", "kids", "indoor"],
    },
    {
      id: "ca-mauterndorf",
      name: "טירת מאוטרנדורף",
      nameLatin: "Burg Mauterndorf",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.1417, lng: 13.6797 },
      priority: "optional",
      duration: "2–3 h",
      weather: "any",
      travelNote: "~40 דק׳ מאלטנמרקט",
      description:
        "טירה קטנה וידידותית מאוד לילדים עם סיפור מודרך באוזניות, חדר התחפשות אבירים וטיפוס למגדל. שקטה וזולה יותר מהוהנוורפן.",
      tags: ["castle", "kids", "quiet"],
    },
    {
      id: "ca-radstadt",
      name: "חומות העיר מימי הביניים, רדשטאדט",
      nameLatin: "Radstadt medieval town walls",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.3856, lng: 13.4553 },
      priority: "optional",
      duration: "1–2 h",
      weather: "any",
      travelNote: "~8 דק׳ מאלטנמרקט",
      description:
        "עיר עתיקה מוקפת חומה עם מגדלים, גלידה והסופרמרקטים ובית המרקחת האמיתיים הקרובים ביותר לבית. טיול ערב מושלם ללא מחויבות.",
      tags: ["free", "short", "closest", "shops"],
    },
    {
      id: "ca-seegrotte",
      name: "מערת האגם זגרוטה הינטרברול",
      nameLatin: "Seegrotte Hinterbrühl",
      category: "castle",
      region: "enroute",
      coords: { lat: 48.0619, lng: 16.2472 },
      priority: "high",
      duration: "1.5 h",
      weather: "rain",
      travelNote: "~30 דק׳ מוינה · בצד ה-A2/A21 של העיר",
      description:
        "סיור שיט על האגם התת-קרקעי הגדול באירופה בתוך מכרה גבס לשעבר. 9°C קבוע — קחו מעילים. טיול אידאלי ליום גשום מחוץ לוינה, או עצירה בדרך חזרה.",
      tags: ["rainy day", "underground", "boat", "indoor"],
    },
    {
      id: "ca-schloss-hof",
      name: "ארמון שלוס הוף, מרשפלד",
      nameLatin: "Schloss Hof, Marchfeld",
      category: "castle",
      region: "enroute",
      coords: { lat: 48.1958, lng: 16.8322 },
      priority: "optional",
      duration: "half day",
      weather: "sun",
      travelNote: "~45 דק׳ ממזרח לוינה",
      description:
        "ארמון בארוקי עם גנים מדורגים וחווה חקלאית פעילה מלאה חיות — הידידותי ביותר לילדים מבין ארמונות אזור וינה, ופחות עמוס בהרבה מ-Schönbrunn.",
      tags: ["palace", "animals", "gardens", "quiet"],
    },
    {
      id: "ca-spielzeugmuseum",
      name: "מוזיאון הצעצועים, זלצבורג",
      nameLatin: "Spielzeugmuseum, Salzburg",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.8, lng: 13.04 },
      navQuery: "Spielzeugmuseum Salzburg, Austria",
      priority: "optional",
      duration: "1.5 h",
      weather: "rain",
      travelNote: "~55 דק׳ מאלטנמרקט · בעיר העתיקה של זלצבורג",
      description:
        "מוזיאון צעצועים משחקי בלב זלצבורג עם אזורי משחק, בובות ותחנות התנסות. תוספת קטנה ונחמדה ליום גשום בעיר, במיוחד עם ילדים צעירים.",
      tags: ["rainy day", "museum", "kids", "indoor"],
    },
    {
      id: "ca-altaussee",
      name: "מכרה המלח אלטאאוסה",
      nameLatin: "Salzwelten Altaussee",
      category: "castle",
      region: "salzburgerland",
      coords: { lat: 47.6392, lng: 13.7644 },
      navQuery: "Salzwelten Altaussee, Austria",
      priority: "high",
      duration: "2–3 h",
      weather: "rain",
      travelNote: "~שעה 20 דק׳ מאלטנמרקט",
      description:
        "חלופה מצוינת למכרה המלח של הלשטאט (שסגור לעבודות עד 1.9.2026): רכבת כורים אל תוך ההר, מגלשות עץ וסיפור על אוצר האמנות שהוסתר כאן במלחמה. קריר בפנים — קחו מעילים.",
      tags: ["rainy day", "kids", "underground", "salt mine"],
    },

    /* ===== VIENNA HIGHLIGHTS ===== */
    {
      id: "vi-schoenbrunn",
      name: "ארמון וגני שנברון",
      nameLatin: "Schönbrunn Palace & gardens",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1845, lng: 16.3122 },
      priority: "must",
      duration: "half day",
      weather: "any",
      travelNote: "רכבת U4 שנברון",
      description:
        "ארמון קיסרי עם ׳הסיור הגדול׳ בחדרי המדינה, פארק ענק חינם, תצפית הגלוריאטה, מבוך ומוזיאון ילדים. הזמינו כרטיס לשעה מוגדרת אונליין — התור בקופה אכזרי באוגוסט.",
      tags: ["palace", "book ahead", "gardens", "kids"],
    },
    {
      id: "vi-tiergarten",
      name: "גן החיות טירגרטן שנברון",
      nameLatin: "Tiergarten Schönbrunn (zoo)",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1817, lng: 16.3021 },
      priority: "must",
      duration: "4–5 h",
      weather: "any",
      travelNote: "רכבת U4 היצינג · אותו פארק כמו הארמון",
      description:
        "גן החיות העתיק בעולם, ובאופן עקבי מדורג מהטובים ביותר: פנדות, בית גשם, פולריום ואקווריום. הרבה ביתנים מקורים, אז שורד גשם טוב יותר מרוב גני החיות.",
      tags: ["kids", "zoo", "partly indoor"],
    },
    {
      id: "vi-prater",
      name: "הגלגל הענק ופארק השעשועים פראטר",
      nameLatin: "Wiener Riesenrad & Prater funfair",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.2166, lng: 16.3958 },
      priority: "must",
      duration: "3–4 h",
      weather: "any",
      travelNote: "רכבת U1/U2 פראטרשטרן",
      description:
        "פארק שעשועים עם כניסה חינם — משלמים לכל אטרקציה — שעוגן בגלגל הענק מ-1897. הכול מקרוסלות לפעוטות ועד רכבות שדים עם לולאות, הכי טוב אחרי החשכה כשהכול מואר.",
      tags: ["kids", "free entry", "evening"],
    },
    {
      id: "vi-stephansdom",
      name: "קתדרלת שטפן ומרכז העיר",
      nameLatin: "Stephansdom & city centre",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.2085, lng: 16.3731 },
      priority: "must",
      duration: "2–3 h",
      weather: "any",
      travelNote: "רכבת U1/U3 שטפנספלאץ",
      description:
        "קתדרלה גותית ממש במרכז וינה: קטקומבות, מעלית למגדל הצפוני, 343 מדרגות למגדל הדרומי. התחילו כל סיור רגלי של הגראבן וקרנטנר שטראסה כאן.",
      tags: ["free entry", "church", "walkable"],
    },
    {
      id: "vi-haus-des-meeres",
      name: "האוס דה מארס — אקווה טרה זו",
      nameLatin: "Haus des Meeres aqua terra zoo",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1966, lng: 16.3538 },
      priority: "high",
      duration: "2–3 h",
      weather: "rain",
      travelNote: "רכבת U3 נויבאוגסה",
      description:
        "אקווריום ובית טרופי שנבנו בתוך מגדל נ.מ. מלחמת העולם השנייה, עם כרישים, ציפורים מעופפות חופשי ותצפית מבית קפה על הגג מעל העיר. כולו מקורה — הבחירה המובילה ליום גשום בוינה.",
      tags: ["rainy day", "kids", "indoor", "aquarium"],
    },
    {
      id: "vi-nhm",
      name: "המוזיאון להיסטוריה של הטבע",
      nameLatin: "Naturhistorisches Museum",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.2053, lng: 16.3595 },
      priority: "high",
      duration: "2–3 h",
      weather: "rain",
      travelNote: "רכבת U2/U3 פולקסטיאטר",
      description:
        "שלדי דינוזאורים, ונוס מווילנדורף בת 29,500 שנה, מטאוריטים ופלנטריום דיגיטלי בבניין שהוא ארמון. כניסה חינם עד גיל 19.",
      tags: ["rainy day", "museum", "kids", "free for kids", "indoor"],
    },
    {
      id: "vi-technisches",
      name: "המוזיאון הטכני של וינה",
      nameLatin: "Technisches Museum Wien",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1901, lng: 16.3182 },
      priority: "high",
      duration: "3 h",
      weather: "rain",
      travelNote: "רכבת U4 שנברון + 10 דק׳ הליכה",
      description:
        "קטרים, מטוסים, שחזור מכרה פחם וקומת פיזיקה ענקית עם תחנות התנסות לילדים. המוזיאון האינטראקטיבי ביותר בעיר, ולעיתים רחוקות עמוס. חינם עד גיל 19.",
      tags: ["rainy day", "museum", "kids", "hands-on", "indoor"],
    },
    {
      id: "vi-belvedere",
      name: "ארמון בלוודרה וקלימט",
      nameLatin: "Schloss Belvedere & Klimt",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1915, lng: 16.3809 },
      priority: "optional",
      duration: "2 h",
      weather: "any",
      travelNote: "חשמלית D בלוודרה",
      description:
        "ארמון בארוקי שמחזיק את ׳הנשיקה׳ של קלימט, עם גנים מסוגננים שהכניסה אליהם חינם. יותר למבוגרים — שלבו עם ארוחת צהריים בנשמרקט.",
      tags: ["art", "gardens", "indoor"],
    },
    {
      id: "vi-donauturm",
      name: "מגדל הדנובה (דונאוטורם)",
      nameLatin: "Donauturm (Danube Tower)",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.2408, lng: 16.4106 },
      priority: "optional",
      duration: "1.5 h",
      weather: "any",
      travelNote: "רכבת U1 אלטה דונאו + אוטובוס",
      description:
        "מגדל בגובה 252 מ׳ עם המעלית המהירה באוסטריה, מרפסת חיצונית ומסעדה מסתובבת. תצפיות בערב בהיר על העיר והדנובה.",
      tags: ["view", "evening"],
    },
    {
      id: "vi-time-travel",
      name: "מסע בזמן וינה",
      nameLatin: "Time Travel Vienna",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.2088, lng: 16.3702 },
      priority: "optional",
      duration: "1.5 h",
      weather: "rain",
      travelNote: "רכבת U1/U3 שטפנספלאץ",
      description:
        "קולנוע 5D, אנימטרוניקה ומתקן שמספר את ההיסטוריה של וינה ב-50 דקות. תיירותי, מקורה, ובאמת כיף לילדים כשיורד גשם.",
      tags: ["rainy day", "kids", "indoor"],
    },
    {
      id: "vi-rathausplatz",
      name: "פסטיבל הסרטים בכיכר העירייה (ערבי אוגוסט)",
      nameLatin: "Rathausplatz film festival (August evenings)",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.2107, lng: 16.3572 },
      priority: "high",
      duration: "evening",
      weather: "sun",
      travelNote: "רכבת U2 ראטהאוס",
      description:
        "סרטי מוזיקה תחת כיפת השמיים חינם על מסך ענק מול בניין העירייה, מוקף דוכני אוכל, כל הקיץ. קחו סוודר והגיעו בסביבות 20:00.",
      tags: ["free", "evening", "food stalls"],
    },
    {
      id: "vi-naschmarkt",
      name: "שוק נשמרקט",
      nameLatin: "Naschmarkt",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1985, lng: 16.3625 },
      priority: "high",
      duration: "1.5–2 h",
      weather: "any",
      travelNote: "רכבת U4 קטנברוקנגסה",
      description:
        "שוק האוכל הגדול של וינה: גבינות, זיתים, דוכנים מזרח-תיכוניים, פירות ועשרות מסעדות קטנות. לכו לארוחת צהריים, ושימו לב שהמחירים יורדים ככל שמתרחקים מקרלספלאץ.",
      tags: ["food", "market", "lunch"],
    },
    {
      id: "vi-kindermuseum",
      name: "מוזיאון הילדים בשנברון",
      nameLatin: "Kindermuseum Schönbrunn (Children's Museum)",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1836, lng: 16.312 },
      navQuery: "Kindermuseum Schönbrunn, Vienna, Austria",
      priority: "high",
      duration: "2 h",
      weather: "any",
      travelNote: "רכבת U4 שנברון · בתוך מתחם הארמון",
      description:
        "מוזיאון התנסות לילדים בתוך שנברון — מתחפשים כנסיכים, מגלים איך חיו במשפחה הקיסרית ומשחקים. פתוח מדי יום 10:00–17:00. יש כרטיס משולב עם המבוך וגן החיות — שווה לבדוק.",
      tags: ["kids", "museum", "indoor", "hands-on"],
    },
    {
      id: "vi-irrgarten",
      name: "המבוך והלבירינת בשנברון",
      nameLatin: "Schönbrunn Maze & Labyrinth (Irrgarten)",
      category: "vienna",
      region: "vienna",
      coords: { lat: 48.1806, lng: 16.3145 },
      navQuery: "Schönbrunn Irrgarten Labyrinth, Vienna, Austria",
      priority: "optional",
      duration: "1 h",
      weather: "sun",
      travelNote: "רכבת U4 שנברון · בגני הארמון",
      description:
        "מבוך שיחים ומגרש חידות במשחקים אינטראקטיביים בגני שנברון — פורקן אנרגיה מושלם לילדים אחרי חדרי הארמון. באוגוסט פתוח עד 18:30.",
      tags: ["kids", "gardens", "photo"],
    },

    /* ===== FOOD & RESTAURANTS ===== */
    {
      id: "fo-figlmueller",
      name: "פיגלמולר וולצייל, וינה",
      nameLatin: "Figlmüller Wollzeile, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2088, lng: 16.3757 },
      navQuery: "Figlmüller Wollzeile, Vienna, Austria",
      priority: "must",
      duration: "1.5 h",
      weather: "any",
      travelNote: "2 דק׳ מקתדרלת שטפן",
      description:
        "השניצל הוינאי בגודל צלחת שכולם מצלמים — דקיק, חזיר כברירת מחדל, קל לחלוקה בין שני ילדים. הזמינו מקום, או עמדו בתור. סניף בקרשטראסה קולט את העודף.",
      tags: ["schnitzel", "reserve", "classic"],
    },
    {
      id: "fo-plachutta",
      name: "פלכוטה וולצייל, וינה",
      nameLatin: "Plachutta Wollzeile, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2087, lng: 16.3785 },
      navQuery: "Plachutta Wollzeile, Vienna, Austria",
      priority: "high",
      duration: "2 h",
      weather: "any",
      travelNote: "וולצייל, 5 דק׳ משטפנספלאץ",
      description:
        "מוסד הטאפלשפיץ: בשר בקר מבושל שמוגש בסיר הנחושת שלו עם מוח עצם, רסטי וחזרת תפוחים. ארוחת ערב אמיתית בישיבה, מחיר בינוני-גבוה, הזמינו מראש.",
      tags: ["tafelspitz", "reserve", "dinner"],
    },
    {
      id: "fo-schnitzelwirt",
      name: "שניצלוירט, נויבאו, וינה",
      nameLatin: "Schnitzelwirt, Neubau, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2011, lng: 16.3489 },
      navQuery: "Schnitzelwirt Schmidt, Neubaugasse, Vienna, Austria",
      priority: "high",
      duration: "1 h",
      weather: "any",
      travelNote: "רכבת U3 נויבאוגסה",
      description:
        "שניצל ענקי, זול ולא מהודר בבייזל (פונדק) ישן אמיתי — המנות מביסות מבוגרים בקביעות. ידידותי למזומן, בלי טרחה, התרופה המקומית לתמחור התיירותי.",
      tags: ["schnitzel", "cheap", "local"],
    },
    {
      id: "fo-bitzinger",
      name: "דוכן הנקניקיות ביצינגר, כיכר אלברטינה",
      nameLatin: "Bitzinger Würstelstand am Albertinaplatz",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2041, lng: 16.369 },
      navQuery: "Bitzinger Würstelstand Albertina, Vienna, Austria",
      priority: "high",
      duration: "20 min",
      weather: "any",
      travelNote: "מאחורי האופרה",
      description:
        "דוכן הנקניקיות הטוב בעיר: קֵזקריינר עם חרדל ולחמנייה, בעמידה ליד באי האופרה. פתוח עד מאוחר, והארוחה הטובה הזולה ביותר במרכז.",
      tags: ["street food", "cheap", "late night", "quick"],
    },
    {
      id: "fo-cafe-central",
      name: "קפה סנטרל, וינה",
      nameLatin: "Café Central, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2103, lng: 16.3658 },
      navQuery: "Café Central, Herrengasse, Vienna, Austria",
      priority: "high",
      duration: "1 h",
      weather: "rain",
      travelNote: "רכבת U3 הרנגסה",
      description:
        "בית קפה מקומר מהמאה ה-19 שבו התווכחו פרויד וטרוצקי. בואו לאפפלשטרודל ומלאנז׳, קבלו תור של 20 דקות, ואל תמהרו לקום.",
      tags: ["coffee house", "cake", "queue", "indoor"],
    },
    {
      id: "fo-demel",
      name: "דמל, וינה",
      nameLatin: "Demel, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2081, lng: 16.3672 },
      navQuery: "Demel, Kohlmarkt, Vienna, Austria",
      priority: "optional",
      duration: "1 h",
      weather: "rain",
      travelNote: "קולמרקט, ליד ההופבורג",
      description:
        "קונדיטור קיסרי עם מטבח מאחורי זכוכית שאפשר לצפות בו — זאכרטורטה, סיגליות מסוכרות, אנה טורטה. יקר, ושווה ביקור אחד בשביל התיאטרליות של זה.",
      tags: ["cake", "coffee house", "indoor"],
    },
    {
      id: "fo-milk-honey",
      name: "מילק אנד האני (כשר), וינה",
      nameLatin: "Milk'n Honey (kosher), Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2168, lng: 16.3786 },
      navQuery: "Milk n Honey kosher restaurant, Taborstraße, Vienna, Austria",
      priority: "high",
      duration: "1.5 h",
      weather: "any",
      travelNote: "לאופולדשטאדט, רכבת U2 טבורשטרסה",
      description:
        "בית קפה כשר חלבי בסגנון ישראלי ברובע היהודי של וינה. אמתו שעות ישירות — יום שישי נסגר מוקדם ושבת סגור.",
      tags: ["kosher", "dairy", "check hours"],
    },
    {
      id: "fo-bahur-tov",
      name: "בחור טוב (כשר בשרי), וינה",
      nameLatin: "Bahur Tov (kosher meat), Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.216, lng: 16.38 },
      navQuery: "Bahur Tov kosher restaurant, Taborstraße, Vienna, Austria",
      priority: "high",
      duration: "1.5 h",
      weather: "any",
      travelNote: "לאופולדשטאדט, רכבת U2 טבורשטרסה",
      description:
        "גריל כשר בלאופולדשטאדט — שווארמה, קבב, חומוס. אותו רחוב של כמה מאפיות כשרות וסופרמרקט אם צריך ציוד לשבוע באלפים.",
      tags: ["kosher", "meat", "check hours"],
    },
    {
      id: "fo-augustiner",
      name: "אוגוסטינר בּרויְשְטוּבְּל, זלצבורג",
      nameLatin: "Augustiner Bräustübl, Salzburg",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.8036, lng: 13.0333 },
      navQuery: "Augustiner Bräustübl, Salzburg, Austria",
      priority: "must",
      duration: "2 h",
      weather: "any",
      travelNote: "~55 דק׳ מאלטנמרקט",
      description:
        "אולם בירה של מנזר שבו שוטפים את ספל האבן, ממלאים אותו מהחבית וקונים אוכל ממסדרון של מעדניות. גן בירה ענק עם ערמונים — נהדר באמת עם ילדים.",
      tags: ["beer garden", "self service", "kids", "cheap"],
    },
    {
      id: "fo-st-peter",
      name: "סנט פטר שטיפטסקולינריום, זלצבורג",
      nameLatin: "St. Peter Stiftskulinarium, Salzburg",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.7975, lng: 13.0444 },
      navQuery: "St. Peter Stiftskulinarium, Salzburg, Austria",
      priority: "optional",
      duration: "2 h",
      weather: "any",
      travelNote: "~55 דק׳ מאלטנמרקט",
      description:
        "טוענת להיות המסעדה העתיקה באירופה, פועלת מ-803 לספירה, במרתפי המנזר. ארוחת ערב לאירוע מיוחד ולא עצירה משפחתית מזדמנת — הזמינו מקום.",
      tags: ["special occasion", "reserve", "historic"],
    },
    {
      id: "fo-oberhofalm",
      name: "מטבח בקתת אוברהופאלם, פילצמוס",
      nameLatin: "Oberhofalm hut kitchen, Filzmoos",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.4361, lng: 13.5228 },
      navQuery: "Oberhofalm, Filzmoos, Austria",
      priority: "must",
      duration: "1.5 h",
      weather: "sun",
      travelNote: "~25 דק׳ מאלטנמרקט",
      description:
        "קייזרשמארן, קסנוקן ולימונדה ביתית על מרפסת שמש מתחת לבישופסמיצה. ארוחת הצהריים הכי ׳אוסטרית׳ של הטיול. מזומן הכי בטוח, שעות היום בלבד.",
      tags: ["hut food", "cash", "view", "lunch"],
    },
    {
      id: "fo-kirchenwirt-altenmarkt",
      name: "גסטהוף כפרי, מרכז אלטנמרקט",
      nameLatin: "Village Gasthof, Altenmarkt centre",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.3767, lng: 13.42 },
      navQuery: "Gasthof restaurant, Altenmarkt im Pongau, Austria",
      priority: "high",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~5 דק׳ מהבית",
      description:
        "אופציה בהליכה מהבית לערבים עייפים — שניצל, גולאש, מרקים. חפשו את הקישור במפה ובחרו לפי הביקורות העדכניות; מטבחים כפריים לרוב נסגרים עד 20:30 ולוקחים יום מנוחה שבועי.",
      tags: ["closest", "dinner", "verify"],
    },
    {
      id: "fo-grafenwirt-wagrain",
      name: "צום גרפנוירט, וגראין",
      nameLatin: "Zum Grafenwirt, Wagrain",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.3325, lng: 13.3006 },
      navQuery: "Zum Grafenwirt, Wagrain, Austria",
      priority: "optional",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~15 דק׳ מאלטנמרקט",
      description:
        "פרשנות מודרנית לבישול אזורי בכפר וגראין, עם גן. שילוב טבעי עם אחר צהריים ברכבלית גרפנברג.",
      tags: ["dinner", "garden"],
    },
    {
      id: "fo-supermarkt-radstadt",
      name: "סופרמרקטים ובית מרקחת, רדשטאדט",
      nameLatin: "Supermarkets & pharmacy, Radstadt",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.3856, lng: 13.4553 },
      navQuery: "Billa Radstadt, Austria",
      priority: "must",
      duration: "45 min",
      weather: "any",
      travelNote: "~8 דק׳ מהבית",
      description:
        "עצירה מעשית: Billa/SPAR/Hofer ובית מרקחת. הכול נסגר בימי ראשון בכל אוסטריה — עשו את הקנייה הגדולה בערב ההגעה בשבת 18.08 או בבוקר שבת.",
      tags: ["practical", "closed sundays", "shops"],
    },
    {
      id: "fo-rosner",
      name: "גסטהוף רוזנר, אלטנמרקט",
      nameLatin: "Gasthof Rosner, Altenmarkt",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.3778, lng: 13.4212 },
      navQuery: "Gasthof Rosner, Altenmarkt im Pongau, Austria",
      priority: "high",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~5 דק׳ מהבית",
      description:
        "אוכל אוסטרי מסורתי וביתי במרכז אלטנמרקט — שניצל, גולאש וקנודל בהגשה מזמינה. אופציה נוחה בהליכה מהבית לערב רגוע.",
      tags: ["local", "dinner", "closest"],
    },
    {
      id: "fo-sattelbauer",
      name: "ברגגסטהוף זאטלבאואר, פלאכאו",
      nameLatin: "Berggasthof Sattelbauer, Flachau",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.3392, lng: 13.3922 },
      navQuery: "Berggasthof Sattelbauer, Flachau, Austria",
      priority: "high",
      duration: "1.5 h",
      weather: "sun",
      travelNote: "~15 דק׳ מאלטנמרקט",
      description:
        "מסעדת הרים ציורית מעל פלאכאו עם נוף פתוח, אוכל אזורי טוב וגן משחקים לילדים בחוץ. משתלב מצוין עם יום ב-Lucky Flitzer.",
      tags: ["hut food", "view", "kids"],
    },
    {
      id: "fo-steinerwirt",
      name: "שטיינרוירט, גוזאו",
      nameLatin: "Steinerwirt, Gosau",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.5847, lng: 13.5378 },
      navQuery: "Steinerwirt, Gosau, Austria",
      priority: "optional",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~שעה 10 דק׳ מאלטנמרקט",
      description:
        "אוכל אלפיני ביתי באזור גוזאו/הלשטאט, דגים טריים ואווירה נעימה. אמתו שעות וזמינות מקום מראש — מטבחי כפר לרוב סוגרים מוקדם.",
      tags: ["local", "dinner", "verify"],
    },
    {
      id: "fo-doellerer",
      name: "דלרר, גולינג",
      nameLatin: "Döllerer, Golling an der Salzach",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.5967, lng: 13.1653 },
      navQuery: "Döllerer, Golling an der Salzach, Austria",
      priority: "optional",
      duration: "2 h",
      weather: "any",
      travelNote: "~35 דק׳ מאלטנמרקט",
      description:
        "מטבח אוסטרי משודרג ומוערך בגולינג — מסעדת אירוח, ׳וירטסהאוס׳ יומיומי ומרתף יין מפורסם. לארוחה מיוחדת; הזמינו מקום מראש.",
      tags: ["special occasion", "reserve", "local"],
    },
    {
      id: "fo-lugeck",
      name: "לוגק, וינה",
      nameLatin: "Lugeck Figlmüller, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2094, lng: 16.3762 },
      navQuery: "Lugeck, Vienna, Austria",
      priority: "high",
      duration: "1.5 h",
      weather: "any",
      travelNote: "2 דק׳ מקתדרלת שטפן",
      description:
        "גרסה מודרנית ונהדרת למטבח וינאי קלאסי מבית פיגלמילר — שניצל, גולאש וקנֵדל, בסביבה מרווחת יותר מהסניף המקורי. ליד קתדרלת שטפן.",
      tags: ["schnitzel", "classic", "reserve"],
    },
    {
      id: "fo-sacher",
      name: "קפה זאכר, וינה",
      nameLatin: "Café Sacher, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2036, lng: 16.369 },
      navQuery: "Café Sacher Wien, Austria",
      priority: "high",
      duration: "1 h",
      weather: "rain",
      travelNote: "ליד האופרה",
      description:
        "בית הקפה ההיסטורי מאחורי האופרה, בית הזאכרטורטה המקורית. קבלו תור בשעות העמוסות, הזמינו את העוגה עם קצפת ומלאנז׳.",
      tags: ["cake", "coffee house", "classic", "indoor"],
    },
    {
      id: "fo-zanoni",
      name: "זנוני אנד זנוני, וינה",
      nameLatin: "Zanoni & Zanoni, Vienna",
      category: "food",
      region: "vienna",
      coords: { lat: 48.2103, lng: 16.3766 },
      navQuery: "Zanoni & Zanoni, Vienna, Austria",
      priority: "optional",
      duration: "45 min",
      weather: "any",
      travelNote: "~3 דק׳ משטפנספלאץ",
      description:
        "גלידרייה איטלקית ותיקה ואהובה ליד שטפנספלאץ, פתוחה עד מאוחר. עצירת מתוק זריזה אחרי סיור במרכז — יש תורים בערב אבל נעים.",
      tags: ["quick", "kids", "late night"],
    },
    {
      id: "fo-roemerkeller",
      name: "רסטורנט רמרקלר, אלטנמרקט",
      nameLatin: "Restaurant Römerkeller, Altenmarkt",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.376, lng: 13.4195 },
      navQuery: "Restaurant Römerkeller, Altenmarkt im Pongau, Austria",
      priority: "optional",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~5 דק׳ מהבית",
      description:
        "מסעדה נעימה במרכז אלטנמרקט לערב רגוע בהליכה מהבית — אוכל אוסטרי ופיצות. אמתו שעות; מטבחי כפר לרוב סוגרים מוקדם.",
      tags: ["local", "dinner", "closest"],
    },
    {
      id: "fo-kessei",
      name: "וירטסהאוס סקסאי, אלטנמרקט/צאוכנזה",
      nameLatin: "Wirtshaus s'Kessei, Altenmarkt/Zauchensee",
      category: "food",
      region: "salzburgerland",
      coords: { lat: 47.377, lng: 13.42 },
      navQuery: "s'Kessei, Altenmarkt im Pongau, Austria",
      priority: "optional",
      duration: "1.5 h",
      weather: "any",
      travelNote: "~5 דק׳ מהבית",
      description:
        "וירטסהאוס/בר מקומי לארוחת ערב או משקה באזור אלטנמרקט/צאוכנזה. אופציה קרובה נוספת לערבים; אמתו שעות וזמינות מקום מראש.",
      tags: ["local", "dinner", "verify"],
    },
  ],
};
